language: ruby
cache: bundler
before_install:
  # install Node version from .node-version
  - nvm install
  - nvm use
script: bundle exec middleman build --verbose

env:
  global:
  # CloudFoundry credentials for deployment
  - CF_API="https://api.cloud.service.gov.uk"
  - CF_ORG="govuk-design-system"
  - CF_SPACE="prototype-kit-training"
  - CF_USERNAME="design-system-deploy+prototype-kit@digital.cabinet-office.gov.uk"
  # CF_PASSWORD
  - secure: "UrcAlwGWTWbQNQ4h30/hGfEYxs9BHZJEXgdZYyZTnVeQUmyKkIZhGoHe/mglOjDJfRrvOELv+J1ZSLM/pnkcVUCNHRBtkI8sZDP/ozeYSBNc6glkE+X03JgUG5S4KuJq3ziKi2eS8a14Jyi3XsLqOjKLDRwL3VmQTy9AjiZj+3DYfzN/Cur7r65Bm97o8aWY/nP30B+O4ovEJ55lXd8zSW49Cdxo3QfQB0qs9NMKm/gQxJ/MeBK7hRdnfw/nhvqnKyctvBeSEKBe/xGgszgkhOnTIrGVfzpNlpEEE5ZOtiWFgBjnJmhWb9llARueZuwUqU8a9rhg1oEobb1jnkdE0xD+MY1Gwh/9mL+wuHXTmKCZvZEATquQBRZuZql9IroQabiIKDW9r3vSagbaKMB6Y5wKZn411qoHG+LKj02eX1ozCUk4GL/6x4JgeJVu3fqnQ/gQbcUQ4mTGgLovNRpK0E9Qcq2OwE5PYZM8EKGLIVqxQ5rCLxArWzAOAvvd1bHKiHabnfjZNdLYZLpl7bGAZKU1Ljpjx0oFVkC1oa7xjgDGgPOehdrEkFMh8vp6V/alty+93nt4W+8q6M4ZRkUdIs5EaXy+vHim+JmSw5t+O+DdSgkqJf8Mzjbm0hNztVF+fHR5Ly454Q+/ckKGD+Jrcxtp2ubSPNaLHQWlfb/DPow="

# Install CloudFoundry CLI tools
before_deploy:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf7-cli

# We use a script rather than using Travis' built in CloudFoundry provider
# because it does not support zero downtime deploys
# (https://github.com/travis-ci/dpl/pull/610)
deploy:
  provider: script
  script: "./bin/deploy-travis"
  # We build the site as part of the build, so we want to keep it so it can be
  # deployed!
  skip_cleanup: true
  on:
    branch: main
