language: ruby
cache: bundler
before_install:
  # install Node version from .node-version
  - nvm install
  - nvm use
script: bundle exec middleman build --verbose

env:
  global:
  # CloudFoundry credentials for deployment
  - CF_API="https://api.cloud.service.gov.uk"
  - CF_ORG="govuk-design-system"
  - CF_SPACE="prototype-kit-training"
  - CF_USERNAME="design-system-deploy+prototype-kit@digital.cabinet-office.gov.uk"
  # CF_PASSWORD
  - secure: "lRCYL4M4bm4BSUkFwfDWxyLC89tuj5J3Y3VGgq4vJjMfKwynucdWsPsJUvJ9uo7DOyhCcWKsgaBmEsqYSzMmGLRa/0H2tjWAWObaeBP3ocwSnWRJ3v8oY3bY3XQ4C8XgsTu8tVhVNQc0ClKUmQ7aRp2arNL7FqIVVREH1W/yTHZgmeCv2vWPsTRg/41fFJNMsWXaxi6WSXKsED/pDFGF5TXh6NqgwaHuxOri6e7JeAKs7AzcBPmrY7npVqh+dnx+PUkV/abCZkOi4NgCdMffO1OzlJa5dih0TzGApk50wxOMWFL3WAm6T+fb7MOtfKdrWxOQ3CrkiI7sxUzzZp6/nUVxNc1ZQlbdCLNLn0iGR7fij/Jk3Xy3XAKdTaKjqUdSJRNuM8c2rr/FH8eMXICjpmICVY/7XMkgvYJ/JeTZD0UWoz/zTCEBlIjsBgsAlJmi39zS5X31Y5HyK1G4kOv3k7vTfW2xSjJnKaTh7Zi5mF6piFiUL9gx3nIZubVv8qCfiRk+0gZXd4KiUL/yLcPnkuc7QQGFP+YZgtCEsxH6UtuG9xKxYOnoH1PCEmXYENliep9nb3krvFXKkFA0jYs5ayeiFLs3j8Fv3kC2kmF11KKwhLT9aXV/qeXnczsZl+c88xcZDgXHAPXErZkuT5QeQRG5IsX3XpSFIr1gHe25dUI="

# Install CloudFoundry CLI tools
before_deploy:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf7-cli

# We use a script rather than using Travis' built in CloudFoundry provider
# because it does not support zero downtime deploys
# (https://github.com/travis-ci/dpl/pull/610)
deploy:
  provider: script
  script: "./bin/deploy-travis"
  # We build the site as part of the build, so we want to keep it so it can be
  # deployed!
  skip_cleanup: true
  on:
    branch: main
